services:
  - type: web
    name: video-downloader-backend
    env: node
    plan: free
    buildCommand: |
      chmod +x yt-dlp
      npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
